#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"

ANDROID_SDK_ROOT="${ANDROID_SDK_ROOT:-$ROOT_DIR/.android-sdk}"
ANDROID_HOME="${ANDROID_HOME:-$ANDROID_SDK_ROOT}"
ANDROID_API_LEVEL="${ANDROID_API_LEVEL:-35}"
ANDROID_BUILD_TOOLS="${ANDROID_BUILD_TOOLS:-35.0.0}"
ANDROID_NDK_VERSION="${ANDROID_NDK_VERSION:-27.2.12479018}"
ANDROID_CMAKE_VERSION="${ANDROID_CMAKE_VERSION:-3.22.1}"
TOOLCHAIN_PACK_DIR="${TOOLCHAIN_PACK_DIR:-$ROOT_DIR/.toolchain-packs}"

JDK_CANDIDATE=""
if [[ -n "${JAVA_HOME:-}" && -x "${JAVA_HOME}/bin/java" ]]; then
  JDK_CANDIDATE="$JAVA_HOME"
fi

cat <<EOT
ROOT_DIR=$ROOT_DIR
ANDROID_HOME=$ANDROID_HOME
ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT
ANDROID_API_LEVEL=$ANDROID_API_LEVEL
ANDROID_BUILD_TOOLS=$ANDROID_BUILD_TOOLS
ANDROID_NDK_VERSION=$ANDROID_NDK_VERSION
ANDROID_CMAKE_VERSION=$ANDROID_CMAKE_VERSION
TOOLCHAIN_PACK_DIR=$TOOLCHAIN_PACK_DIR
JDK_CANDIDATE=$JDK_CANDIDATE
EOT
