#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

ensure_local_properties_sdk_dir() {
  local local_properties="$REPO_ROOT/local.properties"
  if [[ -f "$local_properties" ]] && grep -Eq '^[[:space:]]*sdk\.dir[[:space:]]*=' "$local_properties"; then
    return 0
  fi

  local sdk_root="${ANDROID_SDK_ROOT:-${ANDROID_HOME:-}}"
  if [[ -z "$sdk_root" ]]; then
    local fallback_candidates=(
      "/usr/local/lib/android/sdk"
      "/usr/lib/android-sdk"
      "/opt/android-sdk"
      "/opt/android-sdk-linux"
      "$HOME/Android/Sdk"
    )
    local candidate
    for candidate in "${fallback_candidates[@]}"; do
      if [[ -d "$candidate" ]]; then
        sdk_root="$candidate"
        echo "[gradle_with_jdk21] ANDROID_SDK_ROOT/ANDROID_HOME ausentes; usando fallback detectado em ${sdk_root}"
        break
      fi
    done
  fi

  if [[ -z "$sdk_root" ]]; then
    local sdkmanager_bin="${ANDROID_SDK_ROOT:-${ANDROID_HOME:-}}/cmdline-tools/latest/bin/sdkmanager"
    if [[ ! -x "$sdkmanager_bin" ]]; then
      sdkmanager_bin="$(command -v sdkmanager || true)"
    fi
    if [[ -n "$sdkmanager_bin" ]]; then
      local resolved_sdkmanager
      resolved_sdkmanager="$(cd "$(dirname "$sdkmanager_bin")" && pwd)/$(basename "$sdkmanager_bin")"
      local inferred_sdk_root
      inferred_sdk_root="$(dirname "$(dirname "$(dirname "$resolved_sdkmanager")")")"
      if [[ -d "$inferred_sdk_root/platform-tools" || -d "$inferred_sdk_root/platforms" ]]; then
        sdk_root="$inferred_sdk_root"
        echo "[gradle_with_jdk21] SDK inferido via sdkmanager em ${sdk_root}"
      fi
    fi
  fi

  if [[ -z "$sdk_root" ]]; then
    echo "ERRO: Android SDK não encontrado (ANDROID_SDK_ROOT/ANDROID_HOME ausentes e nenhum fallback disponível)." >&2
    echo "Ação recomendada: execute './tools/ci/prepare_android_env.sh --sdk-root <CAMINHO_DO_SDK>' ou configure sdk.dir em local.properties." >&2
    exit 4
  fi

  if [[ ! -d "$sdk_root" ]]; then
    echo "ERRO: Android SDK root inválido: ${sdk_root}" >&2
    echo "Ação recomendada: corrija ANDROID_SDK_ROOT/ANDROID_HOME ou sdk.dir em local.properties." >&2
    exit 4
  fi

  local escaped_sdk_root
  escaped_sdk_root="${sdk_root//\\/\\\\}"

  if [[ -f "$local_properties" ]]; then
    {
      echo
      echo "# Auto-generated by tools/gradle_with_jdk21.sh"
      echo "sdk.dir=${escaped_sdk_root}"
    } >> "$local_properties"
  else
    {
      echo "# Auto-generated by tools/gradle_with_jdk21.sh"
      echo "sdk.dir=${escaped_sdk_root}"
    } > "$local_properties"
  fi

  echo "[gradle_with_jdk21] local.properties atualizado com sdk.dir=${sdk_root}"
}

should_require_android_sdk() {
  if [[ "${GRADLE_WITH_JDK21_SKIP_SDK_CHECK:-false}" == "true" ]]; then
    return 1
  fi

  local has_meaningful_arg=false
  local arg
  for arg in "$@"; do
    case "$arg" in
      --version|-v|--help|-h|help|tasks|properties|projects|dependencies|dependencyInsight)
        ;;
      --*)
        # Keep scanning. Flags like --stacktrace should not force SDK checks by themselves.
        ;;
      *)
        has_meaningful_arg=true
        break
        ;;
    esac
  done

  if [[ "$has_meaningful_arg" == "true" ]]; then
    return 0
  fi

  return 1
}

java_major_of() {
  local java_bin="$1"
  "$java_bin" -XshowSettings:properties -version 2>&1 | awk -F= '/java\.specification\.version/ {gsub(/ /,"",$2); print $2; exit}'
}

find_java_home() {
  local candidate

  if [[ -n "${JAVA_HOME:-}" && -x "${JAVA_HOME}/bin/java" ]]; then
    local major
    major="$(java_major_of "${JAVA_HOME}/bin/java" || true)"
    if [[ "$major" == "21" || "$major" == "17" ]]; then
      printf '%s\n' "$JAVA_HOME"
      return 0
    fi
  fi

  local mise_root="${MISE_DATA_DIR:-$HOME/.local/share/mise}/installs/java"
  if [[ -d "$mise_root" ]]; then
    for candidate in "$mise_root"/21* "$mise_root"/17*; do
      if [[ -x "$candidate/bin/java" ]]; then
        printf '%s\n' "$candidate"
        return 0
      fi
    done
  fi

  local candidates=(
    "/usr/lib/jvm/java-21-openjdk-amd64"
    "/usr/lib/jvm/java-21-openjdk"
    "/usr/lib/jvm/temurin-21-jdk-amd64"
    "/usr/lib/jvm/java-17-openjdk-amd64"
    "/usr/lib/jvm/java-17-openjdk"
  )

  local c
  for c in "${candidates[@]}"; do
    if [[ -x "$c/bin/java" ]]; then
      printf '%s\n' "$c"
      return 0
    fi
  done

  return 1
}

JAVA_HOME_DETECTED="$(find_java_home || true)"
if [[ -z "$JAVA_HOME_DETECTED" || ! -x "$JAVA_HOME_DETECTED/bin/java" ]]; then
  echo "ERRO: JDK 21/17 não encontrado. Instale JDK 21 (preferencial) ou JDK 17 e tente novamente." >&2
  exit 2
fi

export JAVA_HOME="$JAVA_HOME_DETECTED"
export PATH="$JAVA_HOME/bin:$PATH"

JAVA_MAJOR="$(java_major_of "$JAVA_HOME/bin/java" || true)"
if [[ "$JAVA_MAJOR" != "21" && "$JAVA_MAJOR" != "17" ]]; then
  echo "ERRO: JDK incompatível ($JAVA_MAJOR). Este wrapper aceita apenas Java 21 ou 17." >&2
  exit 3
fi

echo "[gradle_with_jdk21] JAVA_HOME=$JAVA_HOME (major=$JAVA_MAJOR)"

if should_require_android_sdk "$@"; then
  ensure_local_properties_sdk_dir
fi

if should_require_android_sdk "$@" && [[ -x "$REPO_ROOT/tools/check_android_toolchain.sh" ]]; then
  TOOLCHAIN_CHECK_STRICT="${TOOLCHAIN_CHECK_STRICT:-auto}"
  if [[ "$TOOLCHAIN_CHECK_STRICT" == "auto" ]]; then
    if [[ "${CI:-}" == "true" || -n "${GITHUB_ACTIONS:-}" ]]; then
      TOOLCHAIN_CHECK_STRICT="true"
    else
      TOOLCHAIN_CHECK_STRICT="false"
    fi
  fi

  if [[ "$TOOLCHAIN_CHECK_STRICT" == "true" ]]; then
    "$REPO_ROOT/tools/check_android_toolchain.sh" --quick >/dev/null
  else
    "$REPO_ROOT/tools/check_android_toolchain.sh" --quick >/dev/null || {
      echo "[gradle_with_jdk21] aviso: check_android_toolchain.sh falhou (modo não estrito). Defina TOOLCHAIN_CHECK_STRICT=true para falhar localmente."
    }
  fi
fi

cd "$REPO_ROOT"
exec ./gradlew "$@"
